#!/usr/bin/env python3
"""
Phase F2 — The "axiomatic" leg of the CFS claim.

Claim component: "the Quran is an AXIOMATIC system" — i.e. a finite, minimal set of
axioms/principles from which the rest is generated. We test the defining property of an
axiomatic system: GENERATIVITY / COMPRESSIBILITY. In a genuine axiomatic system a small
kernel generates (almost) all theorems, so the *irreducible residue* (structure no small
kernel generates) is near zero and compressibility is high.

Inputs = the repo's validated Phase-5 compression and Phase-8 principle layers.
"""
import json

CC = json.load(open("generated/compression/compression_statistics.json"))
CV = json.load(open("generated/compression/compression_curve.json"))
PCv= json.load(open("generated/principles/principle_coverage.json"))
IRP= json.load(open("generated/principles/irreducible_principles.json"))

n_concepts = CC["n_concepts"]
intra = PCv["global_intra_fraction"]            # relations a principle GENERATES
inter = PCv["global_inter_fraction"]            # irreducible residue
knee_k = CV["knee"]["foundationality"]["k"]
knee_frac = CV["knee"]["foundationality"]["fraction"]
ratio80 = CC["answers"]["compression_ratio_at_80pct"]
concepts80 = CC["answers"]["concepts_for_80pct"]
compressible = CC["answers"]["compressible"]
dominant = CC["dominant_core"]["single_dominant_core"]
residue_frac = IRP["irreducible_explanatory_residue_fraction"]

# the formal-axiomatic IDEAL: small kernel (<~15%) generates >~80%, residue near 0.
checks = {
  "small_kernel_recovers_80pct (<=20% concepts)": (concepts80/n_concepts) <= 0.20,
  "generativity_high (intra-principle >=0.5)": intra >= 0.5,
  "irreducible_residue_low (<=0.2)": residue_frac <= 0.20,
}
passed = sum(checks.values())

res = {
  "leg": "axiomatic",
  "evidence": {
    "n_concepts": n_concepts,
    "concepts_needed_for_80pct_structure": concepts80,
    "fraction_of_concepts_needed_for_80pct": round(concepts80/n_concepts, 3),
    "compressibility_verdict_phase5": compressible,
    "compression_knee_k": knee_k,
    "structure_recovered_at_knee": round(knee_frac, 3),
    "relations_generated_by_a_principle_intra_fraction": round(intra, 3),
    "irreducible_residue_fraction": round(residue_frac, 3),
    "single_dominant_core_exists": dominant,
  },
  "checks": checks,
  "checks_passed": f"{passed}/{len(checks)}",
  "verdict": (
    "PARTIAL — PROTO-AXIOMATIC, NOT a minimal finite-axiom system. "
    "A dominant generative core exists (single hub), and the structure is consistent, "
    f"but ~{residue_frac*100:.0f}% of relations are irreducible (generated by no single "
    f"principle) and recovering 80% of structure still needs {concepts80}/{n_concepts} "
    f"concepts ({concepts80/n_concepts*100:.0f}%). The defining axiomatic property — a "
    "small kernel generating the whole — does NOT hold strongly."
  ),
}
json.dump(res, open("generated/book-quran-audit/f2_axiomatic.json","w"),
          ensure_ascii=False, indent=2)
print(json.dumps(res, ensure_ascii=False, indent=2))
